version: "3.8"

services:

  accounts:
    image: miros/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-network

  loans:
    image: miros/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-network

  cards:
    image: miros/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-network

networks:
  bank-network: